tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"

brew "mas"
brew "bat"
brew "python@3.8"
brew "cmake"
brew "docker"
brew "exa"
brew "gh"
brew "git"
brew "git-lfs"
brew "http-server"
brew "nvm"
brew "tldr"
brew "wget"
brew "yarn"
brew "zsh"
brew "mongodb/brew/mongodb-community"

cask "clockify"
cask "google-chrome"
cask "iterm2"
cask "mongodb-compass"
cask "notion"
cask "postman"
cask "rectangle"
cask "slack"
cask "spotify"
cask "visual-studio-code"

mas "todoist", id: 585829637
mas "ToothFairy", id: 1191449274